version: '3.4'
volumes:
  dados:
services:
  db_pg:
    image: postgres:13
    ports:
      - 5435:5432
    volumes:
      - dados:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'poc_sl_pg'
      POSTGRES_PASSWORD: docker
  db_mg:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: poc_sl_mgdb
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
    